package com.flipit.ui.dialogs;

import com.flipit.util.IconUtil;
import com.flipit.util.ImageUtil;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class WarningDialog extends JDialog {
    private JPanel contentPane;
    private JButton buttonOK;
    private JButton buttonCancel;
    private JLabel messageLabel;

    private boolean isApproved = false;

    public WarningDialog(Window owner, String title, String message, String confirmText) {
        super(owner, title, ModalityType.APPLICATION_MODAL);
        setContentPane(contentPane);
        getRootPane().setDefaultButton(buttonCancel);

        if (messageLabel != null) {
            int textWidth = ImageUtil.scale(280);
            messageLabel.setText("<html><div style='width: " + textWidth + "px;'>" + message.replaceAll("\n", "<br>") + "</div></html>");

            messageLabel.setIcon(IconUtil.getIcon("WARNING", Color.decode("#ef4444"), ImageUtil.scale(28)));
            messageLabel.setIconTextGap(ImageUtil.scale(14));
        }

        if (buttonOK != null && confirmText != null) {
            buttonOK.setText(confirmText);
        }

        styleUI(owner);

        pack();
        setLocationRelativeTo(owner);

        buttonOK.addActionListener(e -> onOK());
        buttonCancel.addActionListener(e -> onCancel());
        contentPane.registerKeyboardAction(e -> onCancel(),
                KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    private void styleUI(Window owner) {
        float sf = ImageUtil.getScaleFactor();
        contentPane.setBackground(Color.WHITE);
        contentPane.setBorder(BorderFactory.createEmptyBorder(
                ImageUtil.scale(20), ImageUtil.scale(25), ImageUtil.scale(20), ImageUtil.scale(25)
        ));

        Font baseFont = UIManager.getFont("defaultFont");
        if (baseFont == null) baseFont = new Font("SansSerif", Font.PLAIN, 12);

        if (messageLabel != null) {
            messageLabel.setFont(baseFont.deriveFont(Font.BOLD, 14f * sf));
            messageLabel.setForeground(Color.decode("#1a1f36"));
        }

        buttonOK.setBackground(Color.decode("#ef4444"));
        buttonOK.setForeground(Color.WHITE);
        buttonOK.setFont(baseFont.deriveFont(Font.BOLD, 13f * sf));
        buttonOK.setFocusPainted(false);
        buttonOK.setBorderPainted(false);
        buttonOK.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        buttonOK.setPreferredSize(new Dimension(ImageUtil.scale(95), ImageUtil.scale(36)));

        buttonOK.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                buttonOK.setBackground(Color.decode("#dc2626"));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                buttonOK.setBackground(Color.decode("#ef4444"));
            }
        });

        buttonCancel.setBackground(Color.WHITE);
        buttonCancel.setForeground(Color.decode("#64748b"));
        buttonCancel.setFont(baseFont.deriveFont(Font.BOLD, 13f * sf));
        buttonCancel.setFocusPainted(false);
        buttonCancel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        buttonCancel.setPreferredSize(new Dimension(ImageUtil.scale(85), ImageUtil.scale(36)));
        buttonCancel.setBorder(BorderFactory.createLineBorder(Color.decode("#e2e8f0"), Math.max(1, ImageUtil.scale(1))));

        buttonCancel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                buttonCancel.setBorder(BorderFactory.createLineBorder(Color.decode("#94a3b8"), Math.max(1, ImageUtil.scale(1))));
                buttonCancel.setForeground(Color.decode("#475569"));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                buttonCancel.setBorder(BorderFactory.createLineBorder(Color.decode("#e2e8f0"), Math.max(1, ImageUtil.scale(1))));
                buttonCancel.setForeground(Color.decode("#64748b"));
            }
        });

        int maxWidth = owner != null ? owner.getWidth() - ImageUtil.scale(40) : ImageUtil.scale(400);
        int targetWidth = Math.min(ImageUtil.scale(400), maxWidth);

        contentPane.setPreferredSize(null);
        contentPane.setMinimumSize(new Dimension(targetWidth, ImageUtil.scale(160)));
    }

    private void onOK() {
        isApproved = true;
        dispose();
    }

    private void onCancel() {
        isApproved = false;
        dispose();
    }

    public boolean isApproved() {
        return isApproved;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        contentPane.setBackground(new Color(-1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 2, new Insets(10, 0, 0, 0), -1, -1));
        panel1.setBackground(new Color(-1));
        contentPane.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), 8, -1, true, false));
        panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        buttonCancel = new JButton();
        buttonCancel.setText("Cancel");
        panel2.add(buttonCancel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        buttonOK = new JButton();
        buttonOK.setText("OK");
        panel2.add(buttonOK, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        messageLabel = new JLabel();
        messageLabel.setText("Are you sure you want to proceed?");
        contentPane.add(messageLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}